version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: api-platform-db
    environment:
      POSTGRES_DB: api_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    container_name: api-platform-redis
    ports:
      - "6379:6379"

  api-platform:
    build: .
    container_name: api-platform-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/api_platform
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379